import type { IOpenOrder, IOrderLine } from 'src/types/fnb';

export function line(p: Partial<IOrderLine> & { id: string }): IOrderLine {
  return {
    seq: 1,
    status: 'Sent',
    lineType: 'Item',
    productId: 'p-1',
    dishId: 'd-1',
    name: 'Cà phê sữa',
    variantName: null,
    quantity: 1,
    orderedQuantity: p.quantity ?? 1,
    voidedQuantity: 0,
    listPrice: 30000,
    unitPrice: 30000,
    priceOverride: null,
    toppings: [],
    quickNotes: [],
    note: null,
    amount: 30000 * (p.quantity ?? 1),
    ticketId: 'tk-1',
    sentAt: '2026-10-06T08:15:31.200Z',
    movedFromOrderId: null,
    movedFromLineId: null,
    createdAt: '2026-10-06T08:15:31.200Z',
    createdByName: 'Lan',
    flags: [],
    ...p,
  };
}

export function order(p: Partial<IOpenOrder> = {}): IOpenOrder {
  return {
    id: 'o-1',
    version: 1,
    status: 'Open',
    branchId: 'b-1',
    tableId: 't-1',
    tableName: 'Bàn 1',
    areaName: 'Tầng trệt',
    serviceType: 'DineIn',
    orderNo: 42,
    displayNo: '42',
    guestCount: 2,
    customerId: null,
    customerName: null,
    note: null,
    lines: [],
    discount: null,
    totals: { itemCount: 0, subtotal: 0, discountAmount: 0, total: 0 },
    bill: null,
    voidRequiresManager: false,
    payment: null,
    movedToOrderId: null,
    cancelReason: null,
    reviewFlags: [],
    openedAt: '2026-10-06T08:15:30.100Z',
    openedByName: 'Lan',
    updatedAt: '2026-10-06T08:15:31.200Z',
    closedAt: null,
    closedByName: null,
    ...p,
  };
}
